name:
  linklater
version:
  4.0.0.2
author:
  Hao Lian <hi@haolian.org>
maintainer:
  Hao Lian <hi@haolian.org>
synopsis:
  A Haskell library for the Slack API
homepage:
  https://github.com/hlian/linklater
bug-reports:
  https://github.com/hlian/linklater/issues
license:
  BSD3
license-file:
  LICENSE
category:
  Network
description: |
  <https://github.com/hlian/linklater/blob/master/README.md ~please see our lovely README.md~>
default-extensions:
  - FlexibleContexts
  - LambdaCase
  - OverloadedLists
  - OverloadedStrings
  - ScopedTypeVariables
dependencies:
  - aeson
  - base >= 4.9.1.0 && < 5
  - base-prelude
  - bytestring
  - containers
  - exceptions
  - HTTP
  - http-types
  - lens
  - lens-aeson
  - mtl
  - safe-exceptions
  - text
  - uri-bytestring
  - wai
  - wreq
library:
  source-dirs: lib/
tests:
  linklater-tests:
    main: Main.hs
    source-dirs: test/
    dependencies:
      - HTTP
      - linklater
      - tasty
      - tasty-hunit
      - text
